askdjango/urls.py
from django.conf import settings
#from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    # url(r'^accounts/', include('accounts.urls')),
    # url(r'^mychart/', include('mychart.urls')),
    # url(r'', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('mychart/', include('mychart.urls')),
    path('', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import include, url
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.post_new, name='post_new'),
    path('<pk>/', views.post_detail, name='post_detail'),
    path('<pk>/edit/', views.post_edit, name='post_edit'),
    path('<pk>/delete/', views.post_delete, name='post_delete'),
    path('<pk>/like/', views.post_like, name='post_like'),


    path('<post_pk>/comments/', views.comment_list, name='comment_list'),
    path('<post_pk>/comments/new/', views.comment_new, name='comment_new'),
    path('<post_pk>/comments/<pk>/edit/', views.comment_edit, name='comment_edit'),
    path('<post_pk>/comments/<pk>/delete/', views.comment_delete, name='comment_delete'),
    path('comments/<pk>/like/', views.comment_like, name='comment_like'),

    url('^posts\.json$', views.post_list_json),
    url('^api/v1/', include('blog.api')),
    # path('posts\.json', views.post_list_json),
    # path('api/v1/', include('blog.api')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_count = models.PositiveIntegerField(default=0)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self): #
        return reverse('blog:post_detail', args=[self.pk])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,) #on_delete=models.CASCADE, 추가해줬다.
    message = models.TextField()
    photo = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_count = models.PositiveIntegerField(default=0)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    class Meta:
        ordering = ['-id']

# 1:1 원투원
# 1:다 외래키
# 다대다 매니투매니층

blog/forms.py
import re
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message', 'photo']

    def clean_message(self):
        message = self.cleaned_data.get('message', None)
        if message:
            if not re.search(r'[ᄀ-힣]', message):
                raise forms.ValidationError('메세지에 한글이 필요합니다.')
        return message

blog/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404, render, resolve_url
from django.template.defaultfilters import truncatewords
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from rest_framework.renderers import JSONRenderer
from .forms import CommentForm
from .models import Post, Comment
from .serializers import PostSerializer


class PostListView(ListView):
    model = Post
    paginate_by = 5

    def get_template_names(self): #리스트뷰에서 사용하는 함수의 종류중 하나
        if self.request.is_ajax(): #참 or 거짓을 리턴한다.ajax요청시 x-requested-with헤더에 xmlhttprequest값이 전달되는지 확인해줌.
            return ['blog/_post_list.html'] #ajax할떈 이템플릿으로 랜더링.
        return ['blog/index.html']

index = PostListView.as_view()





post_new = CreateView.as_view(model=Post, fields=['title', 'content'])






class PostDetailView(DetailView):
    model = Post

    def render_to_response(self, context):
        if self.request.is_ajax():
            return JsonResponse({
                'title': self.object.title,
                'summary': truncatewords(self.object.content, 100), #truncatewords쓰면 전체글이 아니라 요약된 100단어만 몇글자만..
            })
        # 템플릿 렌더링
        return super().render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm() #comment_form이라는 이름으로 모델폼의 인스턴스를 넘겨줌.
        return context

post_detail = PostDetailView.as_view()







post_edit = UpdateView.as_view(model=Post, fields='__all__')






class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

post_delete = PostDeleteView.as_view()






class CommentListView(ListView):
    model = Comment

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(post__id=self.kwargs['post_pk'])

        latest_comment_id = self.request.GET.get('latest_comment_id', None)
        if latest_comment_id:
            qs = qs.filter(id__gt=latest_comment_id)
        return qs


comment_list = CommentListView .as_view()






class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.post = get_object_or_404(Post, pk=self.kwargs['post_pk'])
        response = super().form_valid(form)

        if self.request.is_ajax(): # render_to_response가 호출되지 않습니다.
            return render(self.request, 'blog/_comment.html', {
                'comment': comment,
            })

        return response


    def get_success_url(self):
        return resolve_url(self.object.post)

    def get_template_names(self):
        if self.request.is_ajax():
            return ['blog/_comment_form.html']
        return ['blog/comment_form.html']

comment_new = CommentCreateView.as_view()





class CommentUpdateView(UpdateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        response = super().form_valid(form)

        if self.request.is_ajax(): # render_to_response가 호출되지 않습니다.
            return render(self.request, 'blog/_comment.html', {
                'comment': self.object,
            })

        return response

    def get_success_url(self):
        return resolve_url(self.object.post)

    def get_template_names(self):
        if self.request.is_ajax():
            return ['blog/_comment_form.html']
        return ['blog/comment_form.html']

comment_edit = CommentUpdateView.as_view()






class CommentDeleteView(DeleteView):
    model = Comment

    def get_success_url(self):
        return resolve_url(self.object.post)

comment_delete = CommentDeleteView.as_view()






#cbv
# class CommentLikeView(UpdateView):
#     model = Comment
#     form_class = CommentForm
#
#     def form_valid(self, form):
#         response = super().form_valid(form)
#
#         if self.request.is_ajax(): # render_to_response가 호출되지 않습니다.
#             return render(self.request, 'blog/_comment.html', {
#                 'comment': self.object,
#             })
#
#         return response
#
#     def get_success_url(self):
#         return resolve_url(self.object.post)
#
#     def get_template_names(self):
#         if self.request.is_ajax():
#             return ['blog/_comment_form.html']
#         return ['blog/comment_form.html']
#
# comment_like = CommentLikeView.as_view()

@login_required
#@require_POST
def comment_like(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.user in comment.like_users.all():
        comment.like_users.remove(request.user)
        print("있음")
    else:
        comment.like_users.add(request.user)
        print("없음")
    comment.like_count = comment.like_users.count()
    comment.save()
    return JsonResponse({'ok': True, 'comment_count': comment.like_count}, safe=False)


def post_list_json(request):
    qs = Post.objects.all()

    serializer = PostSerializer(qs, many=True) #시리얼라이저 할때 매니트루 꼭해준다,
    json_utf8_string = JSONRenderer().render(serializer.data)

    return HttpResponse(json_utf8_string, content_type='application/json; charset=utf-8') # 커스텀 지정





# 좋아요 취소는 안되는거
# @login_required
# # @require_POST
# def post_like(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     post.like_users.add(request.user)
#     post.like_count = post.like_users.count()
#     post.save()
#     return JsonResponse({'ok': True, 'like_count': post.like_count}, safe=False)

@login_required
#@require_POST 되는거
def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
        print("있음")
    else:
        post.like_users.add(request.user)
        print("없음")
    post.like_count = post.like_users.count()
    post.save()
    return JsonResponse({'ok': True, 'like_count': post.like_count}, safe=False)



#
# @login_required
# #@require_POST
# def post_like(request, pk):
#     if request.method=='POST':
#         user = request.user
#         like_users = request.POST.get('pk', None)
#         memo = Post.objects.get(pk=like_users)
#
#         if memo.like_users.filter(id=user.id).exists():
#             memo.like_users.remove(user)
#             message='you cant'
#         else :
#             memo.like_users.add(user)
#             message= 'connect'
#         memo.like_count = memo.like_users.count()
#         memo.save()
#         return JsonResponse({'ok': True, 'like_count': memo.like_count}, safe=False)
#
#

blog/templates/blog/_comment.html
{% load thumbnail %}
<script>
    $(function() {
        //좋아요 버튼 클릭시 발생하는 함수
        $("#post_like_button2_{{  comment.pk }}").click(function () {
            var like_url = $(this).data('url');
            var target_id = $(this).data('target-id');
            console.log(like_url); // -> /1/like/ 가 출력 (첫번째 글 좋아요 버튼 클릭시..)
            $.get(like_url).done(function (data) {
                $('#' + target_id).html(data.comment_count);
                console.log(target_id); // -> post_1_like_count 가 출력.
            }).fail(function () {
                alert('failed');
            });
            return false;
        });



    });
</script>

<div id="comment-{{ comment.pk }}" class="media comment" data-comment-id="{{ comment.pk }}">
    {% if comment.photo %}
    <div class="media-left">
        <a href="#">
            <img src="{% thumbnail comment.photo 100x100 crop %}" class="media-object" />
        </a>
    </div>
    {% endif %}

    <div class="media-body">
        {# <h4 class="media-heading">Media heading</h4> #}

        <p>{{ comment.message }}</p>
        &dash;
        <a href="{% url 'blog:comment_edit' comment.post.pk comment.pk %}" class="modal-form-btn"
           data-target-id="comment-{{ comment.pk }}"><small>{{ comment.updated_at }}</small>
        </a>

        <a href="{% url 'blog:comment_delete' comment.post.pk comment.pk %}"
           class="ajax-post-confirm"
           data-target-id="comment-{{ comment.pk }}"
           data-message="정말 삭제하시겠습니까?">
            <small>삭제</small>
        </a>
        <td>
            <span class="btn btn-primary" id="post_like_button2_{{ comment.pk }}"
                  data-url="{% url 'blog:comment_like' comment.pk %}"
                  data-target-id="comment_{{ comment.id }}_like_count">좋아요
                <span id="comment_{{ comment.id }}_like_count">{{ comment.like_count }}</span></span>
        </td>
    </div>
</div>

blog/templates/blog/_comment_form.html
{% load bootstrap3 %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary" />
</form>

blog/templates/blog/_post_list.html
{% comment %}ajax로 바뀌는 부분만 추가해주는거 레이아웃을 뺀 순수코드만{% endcomment %}
{% for post in post_list %}
    <tr>
        <td>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </td>
    </tr>
{% endfor %}

blog/templates/blog/comment_confirm_delete.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post">
                {% csrf_token %}
                <p class="alert alert-danger">
                정말 삭제하시겠습니까? 후회없죠?
                </p>
                <input type="submit" value="삭제하세요!" class="btn btn-danger" />
            </form>

        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            {% include "blog/_comment_form.html" %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/comment_list.html
{% for comment in comment_list %}
    {% include "blog/_comment.html" %}
{% endfor %}

blog/templates/blog/index.html
{% extends "blog/layout.html" %}
{% load staticfiles %}
<link rel='stylesheet' href="{% static 'blog/post_like.css' %}" />
<script src="{% static 'blog/jquery-1.12.1.js' %}">add_js</script>
<script src="{% static 'blog/post_like.js' %}"></script>

{% block extra_body %}
<script>
$(function() {
    var $win = $(window);
    var is_loading = false;
    var current_page = null;
    var load_more = function() { //read more 버튼
        if ( ! is_loading ) {
            var next_page = (current_page || 1) + 1;  /*current_page가 거짓이면 || 1 사용 */
            var next_page_url = '?page=' + next_page;
            is_loading = true;

            $.get(next_page_url). /*현재 url*/
                done(function(html) {
                    $('#post-list tbody').append(html); /*id가 post_list밑에 tbody에 추가해줌.*/
                    current_page = next_page;
                }).
                fail(function(xhr, textStatus, error) {
                    console.log(textStatus);
                })
                .always(function() {
                    console.log("always");
                    is_loading = false;
                });
        }
    };

    $win.scroll(function() { //윈도우 스크롤 내려도 새로고침 된다.
        var diff = $(document).height() - parseInt($win.height());
        if ( diff == $win.scrollTop() ) {
            console.log("바닥에 왔음.");
            load_more();
        }
    });

    $('#load-more-btn').click(load_more); //load_more버튼 눌러도 글목록 새로고침되고

    $(document).on('click', '#post-list a', function(e) {
        e.preventDefault();
        var detail_url = $(this).attr('href');//pk값이 찍힌다.
        console.log(detail_url);

        $.get(detail_url)
            .done(function(json_obj) {
                var $modal = $('#post-modal');
                $modal.find('.modal-title').html(json_obj.title);
                $modal.find('.modal-body').html(json_obj.summary);
                $modal.find('.btn-detail').attr('href', detail_url);
                $modal.modal();
            })
            .fail(function(xhr, textStatus, error) {
                alert('failed : ' + error);
            });
    });
});
</script>
{% endblock %}

{% block content %}
    <!--리드모어 버튼과 새글쓰기 버튼 부분-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered table-hover" id="post-list">
                    <tbody>
                        {% include "blog/_post_list.html" %}
                    </tbody>
                </table>

                <a id="load-more-btn" class="btn btn-primary">Load More ...</a>

                <hr/>
                <a href="{% url 'blog:post_new' %}" class="btn btn-primary">새 글쓰기</a>
            </div>
        </div>
    </div>

    <!--글제목 눌렀을때 뜨는 모달창-->
    <div class="modal fade" id="post-modal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">포스팅 제목</h5>
                    <button type="button" class="close" data-dismiss="modal">
                        <span>&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ...<br/>
                    ...<br/>
                    ...<br/>
                    ...<br/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
                    <a class="btn btn-primary btn-detail">자세히</a> </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/layout.html
{% extends "layout.html" %}
{% load static_tags %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static_t 'blog/style.css' %}" />
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/layout.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post">
                {% csrf_token %}
                <p class="alert alert-danger">
                    정말 삭제하시겠습니까? 후회없죠?
                </p>
                <input type="submit" value="삭제하세요!" class="btn btn-danger" />
            </form>

        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
{% load bootstrap3 %}

{% block extra_body %}

<script>
$(function() {
    $('#check-comment').click(function(e) {
        e.preventDefault();

        var comment_id = $('#comment-list .comment:first').data('comment-id');

        $.get('{% url "blog:comment_list" post.pk %}', {latest_comment_id: comment_id})
            .done(function(html) {
                $('#comment-list').prepend(html);
            })
            .fail(function() {
                alert('failed : ' + error);
            });
    });

    $.get('{% url "blog:comment_list" post.pk %}')
        .done(function(html) {
            $('#comment-list').html(html);
        })
        .fail(function(xhr, textStatus, error) {
            alert('failed : ' + error);
        });



    //좋아요 버튼 클릭시 발생하는 함수
    $("#post_like_button").click(function() {
        var like_url = $(this).data('url');
        var target_id = $(this).data('target-id');
        console.log(like_url); // -> /1/like/ 가 출력 (첫번째 글 좋아요 버튼 클릭시..)
        $.get(like_url).
            done(function(data) {
                console.log(data);
                $('#' + target_id).html(data.like_count);
                console.log(target_id); // -> post_1_like_count 가 출력.
            }).
            fail(function() {
                alert('failed');
            });
        return false;
    });


});
</script>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1>{{ post.title }}</h1>
            {{ post.content|linebreaks }}

            <hr/>

            <a href="{% url 'blog:comment_new' post.pk %}"
               class="modal-form-btn btn btn-primary btn-block">댓글쓰기</a>

            <a id="check-comment" class="btn btn-primary btn-block">
                새 댓글 체크
            </a>

            <div id="comment-list"></div>

            <hr/>

            <a href="{% url 'blog:index' %}" class="btn btn-primary">목록</a>
            <a href="{% url 'blog:post_edit' post.pk %}" class="btn btn-primary">수정</a>
            <a href="{% url 'blog:post_delete' post.pk %}" class="btn btn-danger">삭제</a>
                <td>
                    <span class="btn btn-primary" id="post_like_button"
                        data-url="{% url 'blog:post_like' pk=post.pk %}"
                        data-target-id="post_{{ post.id }}_like_count">좋아요
                        <span id="post_{{ post.id }}_like_count">{{ post.like_count }}</span></span>
                </td>
        </div>
    </div>
</div>



{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/layout.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary" />
            </form>
        </div>
    </div>
</div>
{% endblock %}